// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPwT8bJXuzfrUYCCZTNnmBH75YxQKB6Sk',
    appId: '1:682403051463:web:ebd1a31e2fb1d2de1c0be2',
    messagingSenderId: '682403051463',
    projectId: 'todo-app-class-mh',
    authDomain: 'todo-app-class-mh.firebaseapp.com',
    storageBucket: 'todo-app-class-mh.firebasestorage.app',
    measurementId: 'G-0CP3KD20KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5TGfSqJuElDWziRreSU7EMEfDoHVMhFo',
    appId: '1:682403051463:android:b586df51ea0afaf11c0be2',
    messagingSenderId: '682403051463',
    projectId: 'todo-app-class-mh',
    storageBucket: 'todo-app-class-mh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7axpk9pgxlv0CAWx8nBIkxrtKsglv34',
    appId: '1:682403051463:ios:77d8bce1bf3b2c491c0be2',
    messagingSenderId: '682403051463',
    projectId: 'todo-app-class-mh',
    storageBucket: 'todo-app-class-mh.firebasestorage.app',
    iosBundleId: 'com.example.todoAppClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7axpk9pgxlv0CAWx8nBIkxrtKsglv34',
    appId: '1:682403051463:ios:77d8bce1bf3b2c491c0be2',
    messagingSenderId: '682403051463',
    projectId: 'todo-app-class-mh',
    storageBucket: 'todo-app-class-mh.firebasestorage.app',
    iosBundleId: 'com.example.todoAppClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPwT8bJXuzfrUYCCZTNnmBH75YxQKB6Sk',
    appId: '1:682403051463:web:2d2bba17a0ecd6ab1c0be2',
    messagingSenderId: '682403051463',
    projectId: 'todo-app-class-mh',
    authDomain: 'todo-app-class-mh.firebaseapp.com',
    storageBucket: 'todo-app-class-mh.firebasestorage.app',
    measurementId: 'G-ZNYZ7NBF1S',
  );
}
